kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/Dockerfile
  context: .
  buildArgs:  
    JFROG_BASE_REPOSITORY: aichor-dev-docker
    JFROG_URL: artifactory.bion.tech

spec:
  operator: jobset
  image: image
  command: "python3 -u main.py --operator=jobset --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  types:
    worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0